// Code generated by metricsgen. DO NOT EDIT.

package sequencer

import (
	"github.com/go-kit/kit/metrics/discard"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
	}
	return &Metrics{
		IsActiveSequencer: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "is_active_sequencer",
			Help:      "Whether this node is currently the active sequencer (1) or not (0).",
		}, labels).With(labelsAndValues...),
		BlocksProducedTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "blocks_produced_total",
			Help:      "Total number of blocks produced by this node while acting as the active sequencer. Only advances on the leader/active node.",
		}, labels).With(labelsAndValues...),
		BlockIntervalSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_interval_seconds",
			Help:      "Whole seconds between consecutive applied blocks (block-timestamp delta).",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 6),
		}, labels).With(labelsAndValues...),
		BlockSizeBytes: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_size_bytes",
			Help:      "Size in bytes of applied V2 blocks.",

			Buckets: stdprometheus.ExponentialBuckets(1024, 2, 16),
		}, labels).With(labelsAndValues...),
		ApplyDurationMilliseconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "apply_duration_milliseconds",
			Help:      "Milliseconds per block-apply step, labeled by step (sig store / geth).",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 14),
		}, append(labels, "step")).With(labelsAndValues...),
		BlockTxs: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_txs",
			Help:      "Number of transactions per applied block.",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 14),
		}, labels).With(labelsAndValues...),
		BroadcastChannelDroppedTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "broadcast_channel_dropped_total",
			Help:      "Total blocks dropped because the local broadcast channel was full.",
		}, labels).With(labelsAndValues...),
		AssembleDurationMilliseconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "assemble_duration_milliseconds",
			Help:      "Milliseconds to assemble a block from the L2 node.",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 14),
		}, labels).With(labelsAndValues...),
		SignDurationMilliseconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "sign_duration_milliseconds",
			Help:      "Milliseconds to sign a produced block.",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 14),
		}, labels).With(labelsAndValues...),
		CommitDurationMilliseconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "commit_duration_milliseconds",
			Help:      "Milliseconds to commit a produced block, labeled by mode (single-node).",

			Buckets: stdprometheus.ExponentialBuckets(1, 2, 14),
		}, append(labels, "mode")).With(labelsAndValues...),
		BroadcastChannelDepth: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "broadcast_channel_depth",
			Help:      "Current depth of the local broadcast channel.",
		}, labels).With(labelsAndValues...),
		BcastSyncGap: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_sync_gap",
			Help:      "Number of blocks this node is behind the broadcast tip.",
		}, labels).With(labelsAndValues...),
		BcastBlocksAppliedTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_blocks_applied_total",
			Help:      "Total V2 blocks applied via the broadcast reactor, labeled by source (p2p / cache).",
		}, append(labels, "source")).With(labelsAndValues...),
		BcastRoutinesStarted: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_routines_started",
			Help:      "Whether the broadcast reactor routines are running (1) or stopped (0).",
		}, labels).With(labelsAndValues...),
		BcastPeersBannedTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_peers_banned_total",
			Help:      "Total peers banned by the broadcast reactor, labeled by reason. An invalid-signature (forged) block bans its sender and is surfaced here.",
		}, append(labels, "reason")).With(labelsAndValues...),
		BcastPendingCacheSize: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_pending_cache_size",
			Help:      "Number of blocks held in the pending (out-of-order) cache.",
		}, labels).With(labelsAndValues...),
		BcastBlocksDedupedTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bcast_blocks_deduped_total",
			Help:      "Total inbound blocks dropped as already-seen duplicates.",
		}, labels).With(labelsAndValues...),
		SyncV2BlocksTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "sync_v2_blocks_total",
			Help:      "Total V2 blocks applied via the blocksync catch-up path. The apply rate is derived on the query side with rate(...) — no float gauge is kept.",
		}, labels).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		IsActiveSequencer:            discard.NewGauge(),
		BlocksProducedTotal:          discard.NewCounter(),
		BlockIntervalSeconds:         discard.NewHistogram(),
		BlockSizeBytes:               discard.NewHistogram(),
		ApplyDurationMilliseconds:    discard.NewHistogram(),
		BlockTxs:                     discard.NewHistogram(),
		BroadcastChannelDroppedTotal: discard.NewCounter(),
		AssembleDurationMilliseconds: discard.NewHistogram(),
		SignDurationMilliseconds:     discard.NewHistogram(),
		CommitDurationMilliseconds:   discard.NewHistogram(),
		BroadcastChannelDepth:        discard.NewGauge(),
		BcastSyncGap:                 discard.NewGauge(),
		BcastBlocksAppliedTotal:      discard.NewCounter(),
		BcastRoutinesStarted:         discard.NewGauge(),
		BcastPeersBannedTotal:        discard.NewCounter(),
		BcastPendingCacheSize:        discard.NewGauge(),
		BcastBlocksDedupedTotal:      discard.NewCounter(),
		SyncV2BlocksTotal:            discard.NewCounter(),
	}
}
